// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okykxpgrzarurkgmhkrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9reWt4cGdyemFydXJrZ21oa3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MzYxMDcsImV4cCI6MjA1NTAxMjEwN30.83FVAOEXsGDTV_9e-ynp7WSU5w-a2O27h_CF0SGkqIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);